# 输入文件配置
input:
  excel_file: "~/Code/WFOX-001-202504.xlsx"

# 输出文件配置
output:
  pdf_file: "output.pdf"     # 输出的PDF文件路径

# 卡片内容配置
card:
  album_name: "Life Blossom"
  additional_info:           # 额外信息，每行一个
    - "兑换网址: https://www.dizzylab.net/redeem"
  background: "background.png"  # 背景图片路径
  personal_logo: "personal_logo.png"  # 个人logo路径

# 布局配置
layout:
  grid:
    columns: 2              # 每行卡片数量
    rows: 5                # 每页行数
  card:
    width: 8               # 卡片宽度(cm)
    height: 5              # 卡片高度(cm)
    margin: 0.5              # 页面边距(cm)
    font_size: 10          # 字体大小 