# 输入文件配置
input:
  excel_file: "~/Code/WFOX-001-202504.xlsx"  # 输入的Excel文件路径

# 输出文件配置
output:
  pdf_file: "WFOX-001-202504.pdf"     # 输出的PDF文件路径，相对于运行脚本的PWD

# 卡片内容配置
card:
  album_name: "Life Blossom"
  additional_info:                 # 额外信息，一个元素一行
    - "兑换网址: https://www.dizzylab.net/redeem"

# 布局配置
layout:
  grid:
    columns: 3                     # 每行卡片数量
    rows: 4                        # 每页行数
  card:
    width: 6                       # 卡片宽度(cm)
    height: 4                      # 卡片高度(cm)
    margin: 1                      # 页面边距(cm)
    font_size: 10                  # 字体大小 